import { Memory } from './types';
import { generateId } from './utils';

const SAMPLE_PHOTOS = (count: number, hue: number): string[] => {
  return Array.from({ length: count }, (_, i) => {
    const h = hue + i * 15;
    const s = 20 + (i % 3) * 5;
    const l = 70 + (i % 2) * 10;
    return `data:image/svg+xml,${encodeURIComponent(
      `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300">
        <rect width="400" height="300" fill="hsl(${h},${s}%,${l}%)" rx="4"/>
        <text x="200" y="150" text-anchor="middle" fill="rgba(48,75,92,0.4)" font-size="14" font-family="serif">📸 照片 ${i + 1}</text>
      </svg>`
    )}`;
  });
};

export const DEMO_MEMORIES: Memory[] = [
  {
    id: 'demo-1',
    color: 'mars',
    title: '第一次一起看海',
    summary: '海风吹过发梢，夕阳把我们的影子拉得很长很长。',
    content:
      '那是我们第一次一起旅行。你穿着那条淡蓝色的裙子，光着脚在沙滩上踩水。海浪一阵一阵涌上来，你笑着躲开，然后又追着浪花跑回去。\n\n我站在后面看着你，觉得整个世界都安静了。夕阳把一切都染成了金色——你的头发、你的笑容、你回头看我时眼里的光。\n\n你说："以后我们每年都来看一次海，好不好？"我说好。\n\n后来我们在沙滩上找了两块小石头，说是我们的"海滩信物"。你的那块是白色的，带着一点天然的纹路，你说像云。我的那块是浅灰色的，像海边的礁石。\n\n石头现在还放在我的书桌上。',
    author: '花阳',
    date: '2024-04-01',
    time: '17:30',
    locationName: '三亚湾',
    city: '三亚',
    country: '中国',
    latitude: 18.2528,
    longitude: 109.5120,
    photos: SAMPLE_PHOTOS(5, 200),
    coverPhoto: '',
    photoCaptions: ['到达海边', '你追着浪花', '夕阳下的背影', '我们的海滩信物', '晚餐时你拍的'],
    tags: ['旅行', '第一次'],
    importance: 3,
    memoryType: 'first',
    visitedStatus: 'visited',
    anniversary: true,
    createdAt: '2024-04-02T10:00:00Z',
    updatedAt: '2024-04-02T10:00:00Z',
    isHidden: false,
  },
  {
    id: 'demo-2',
    color: 'moon',
    title: '傍晚的城市漫步',
    summary: '没有目的地，只是走着走着，就到了心里最柔软的地方。',
    content:
      '那天傍晚本来只是出来买个东西，结果我们沿着梧桐树下的街道走了很久很久。\n\n路灯一盏一盏亮起来，你说很喜欢这种感觉——两个人在陌生的街道上并肩走，不说话也不会尴尬。路过一家小小的花店，你停下来了很久。最后买了一支白色的桔梗，别在我的包上。\n\n"这样你走路的时候就能闻到花香了。"你说。\n\n那支花后来干了，我一直没扔，夹在日记本里。每次翻开都能想起那个傍晚，路灯下的你和淡淡的白色花瓣。',
    author: '灵',
    date: '2024-08-20',
    time: '18:45',
    locationName: '武康路',
    city: '上海',
    country: '中国',
    latitude: 31.2050,
    longitude: 121.4370,
    photos: SAMPLE_PHOTOS(4, 30),
    coverPhoto: '',
    photoCaptions: ['梧桐树影', '路边的花店', '那支白色的桔梗', '路灯下的街道'],
    tags: ['散步', '日常'],
    importance: 2,
    memoryType: 'daily',
    visitedStatus: 'visited',
    anniversary: false,
    createdAt: '2024-08-20T22:00:00Z',
    updatedAt: '2024-08-20T22:00:00Z',
    isHidden: false,
  },
  {
    id: 'demo-3',
    color: 'saturn',
    title: '生日那天的日出',
    summary: '当第一缕阳光照在你脸上时，我知道这是最好的生日礼物。',
    content:
      '你的生日，我偷偷策划了很久。凌晨四点我们就出发了，开车到一个很远的山顶。\n\n山路很黑，你靠在我肩膀上睡着了。到达的时候天边刚刚开始泛白。我们裹着同一件外套坐在石头上等日出。风很大，但你一直在笑。\n\n当太阳从云层里跳出来的那一刻，整个世界都是金色的。我转头看你，你的眼睛里映着光，亮晶晶的。\n\n"生日快乐。"我说。\n你没有说话，把头靠在我肩上。那一刻我觉得，以后的每一个日出都要和你看。',
    author: '花阳',
    date: '2024-10-01',
    time: '06:15',
    locationName: '香山',
    city: '北京',
    country: '中国',
    latitude: 39.9910,
    longitude: 116.1850,
    photos: SAMPLE_PHOTOS(6, 40),
    coverPhoto: '',
    photoCaptions: ['出发时的星空', '山路上的车灯', '天边刚开始泛白', '日出那一瞬间', '你眼睛里有光', '下山时拍的花'],
    tags: ['生日', '纪念日', '惊喜'],
    importance: 3,
    memoryType: 'birthday',
    visitedStatus: 'visited',
    anniversary: true,
    createdAt: '2024-10-02T08:00:00Z',
    updatedAt: '2024-10-02T08:00:00Z',
    isHidden: false,
  },
  {
    id: 'demo-4',
    color: 'neptune',
    title: '初雪',
    summary: '今年的第一场雪，刚好和你在一起。',
    content:
      '早上醒来发现窗外白茫茫的一片。你兴奋地拉着我下楼，像个小孩一样在雪地里踩脚印。\n\n你说要在雪上写字，结果手指冻得通红才歪歪扭扭地写下我们名字的首字母。我用树枝在旁边画了一朵小花。\n\n你说："你看，雪会记住我们的。"\n我说："嗯，等雪化了，春天就记住了。"',
    author: '灵',
    date: '2024-12-15',
    time: '09:30',
    locationName: '西湖',
    city: '杭州',
    country: '中国',
    latitude: 30.2590,
    longitude: 120.1550,
    photos: SAMPLE_PHOTOS(3, 180),
    coverPhoto: '',
    photoCaptions: ['窗外的雪', '雪地上的名字', '断桥残雪'],
    tags: ['日常', '旅行'],
    importance: 2,
    memoryType: 'daily',
    visitedStatus: 'visited',
    anniversary: false,
    createdAt: '2024-12-15T12:00:00Z',
    updatedAt: '2024-12-15T12:00:00Z',
    isHidden: false,
  },
  {
    id: 'demo-5',
    color: 'uranus',
    title: '总有一天我们会一起看极光',
    summary: '你说想在有生之年去一次北欧，去看极光。我记住了。',
    content:
      '那天晚上我们在阳台上看星星。你说小时候的梦想是去看一次极光。\n\n"听说极光会跳舞，绿色的、紫色的，整个天空都是。"你说这话的时候，眼睛亮亮的。\n\n我握着你的手说："等我们攒够了假期和钱，就去。"\n你笑了："那得多久啊？"\n"管它多久，反正这辈子我们有的是时间。"\n\n这是我们未来清单上的第一件事。我相信它一定会实现。',
    author: '花阳',
    date: '2025-01-10',
    time: '22:00',
    locationName: '特罗姆瑟',
    city: 'Tromsø',
    country: '挪威',
    latitude: 69.6496,
    longitude: 18.9560,
    photos: SAMPLE_PHOTOS(2, 260),
    coverPhoto: '',
    photoCaptions: ['想象中极光的颜色', '我们的未来清单'],
    tags: ['未来计划', '旅行'],
    importance: 2,
    memoryType: 'travel',
    visitedStatus: 'future',
    anniversary: false,
    createdAt: '2025-01-10T23:00:00Z',
    updatedAt: '2025-01-10T23:00:00Z',
    isHidden: false,
  },
];
